### PR TITLE
Use ::class

### PR DESCRIPTION
**Pull request by frederikbosch**

### CODE REVIEW

**Comment by harikt** [comment]
I guess this will break for 5.4 and will not be an easy transition for some of them. Eg : cakephp in 5.4 ? and I don't love just for the sake of `::class` we need to push to 5.5 .

**Comment by frederikbosch** [comment]
For the sake of it, we should push people to secure PHP versions. AuraPHP is a high quality brand: if I were you, I would drop support for PHP 5.4 for all packages.

Sideline. I don't understand it. Programmers are screaming security, complaining about Windows XP computers still in use, old browsers versions, etc. But how come that the PHP community is still supporting PHP 5.4? Packages should be PHP 5.6+ if you ask me.

**Comment by harikt** [comment]
@frederikbosch don't close it. This is just my opinion. We can discuss here :) .

**Comment by pmjones** [comment]
The real question here is, since this is targeted at Cake (which is fine with me), what does Cake target for its PHP version?

**Comment by harikt** [comment]
@pmjones good call. It looks 5.5.9 https://github.com/cakephp/cakephp/blob/b2a62aeda541bc3dc251a582dc9807a90c6eeec1/composer.json#L21

**Comment by harikt** [comment]
Update : 
- 3.0.0 [>=5.4.16](https://github.com/cakephp/cakephp/blob/3.0.0/composer.json#L21) 
- 3.2.0 [>=5.5.9](https://github.com/cakephp/cakephp/blob/3.2.0/composer.json#L21)

So I think php version is not bothered for cake ;) .

**Comment by frederikbosch** [comment]
@harikt If you'd like I can update the PR then, require php 5.5 and move to `::class` where possible. What do you think? /cc @pmjones

**Comment by harikt** [comment]
@frederikbosch I don't think you should care too much into my likes / dislikes :-) . It is always just my opinion . At the end of the day it should be @pmjones words for he is the leader.

Looking at 3.2 of cake I believe it will not be having any trouble, so feel free to update the travis and composer.json and anything else, so everything will be green.

**Comment by harikt** [comment]
Hi @frederikbosch ,

If you can make the necessary changes to `composer.json` , `.travis.yml` etc we could probably make use of the same and merge to 2.x .

Thank you

**Pull request merged**
