### PR TITLE
Moving to 5.5+

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by lorenzo** [comment]
I think this code is not needed in 5.5 https://github.com/auraphp/Aura.Intl/blob/2.x/src/IntlFormatter.php#L53-L100

**Comment by harikt** [comment]
Hey @lorenzo , 

Nice to see you here. And thanks for your comments :+1: . Would you like to take part in the process?

We will be more happy to add you.

**Comment by harikt** [comment]
@lorenzo one more thing what is the targetted php version of cakephp ? Can we skip 5.5 itself ?

**Comment by harikt** [comment]
Hi @lorenzo , 

I have made the changes to the code as per your comment. You can see https://github.com/auraphp/Aura.Intl/pull/28/commits/ca855292db1485fa3f90d37f3143235e90b6470c . I am interested to know if we can do a test on cakephp and see if there is anything breaking there or update the code accordingly if any.

Thank you.

**Comment by lorenzo** [comment]
I'll do that tomorrow @harikt :)

**Comment by lorenzo** [comment]
@harikt Sorry I did not answer before, I was away from the computer for the weekend :D

**Comment by lorenzo** [comment]
> @lorenzo one more thing what is the targetted php version of cakephp ? Can we skip 5.5 itself ?

Currently we target 5.5 but next version (maybe in the next 2 months) will be 5.6

**Comment by harikt** [comment]
Closing in favor of https://github.com/auraphp/Aura.Intl/pull/29 .

**Comment by harikt** [comment]
@lorenzo no issues :-) . Take your time.

You may probably want to run against the rebased branch https://github.com/auraphp/Aura.Intl/pull/29 . I hope there will be no trouble and upgrade will be smooth. 

If all are fine we can do release for 2.x or may be 3.x ( @pmjones ? ) . Also if cake will push to 5.6 in next 2 months I am not sure we should stick to 5.5 itself .

Thank you

**Pull request closed without merging**
